site_name: Pomelo
site_description: Dynamic page objects for browser automation.
site_author: Jace Browning

repo_url: https://github.com/jacebrowning/pomelo
edit_uri: https://github.com/jacebrowning/pomelo/edit/develop/docs

theme: readthedocs

markdown_extensions:
  - codehilite:
      linenums: true

nav:
- Home: index.md
- Advanced: advanced.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
